DROP DATABASE IF EXISTS reverb;
CREATE DATABASE reverb;
USE reverb;
CREATE TABLE instruments (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE news (
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255),
  PRIMARY KEY(id)
);